name: markov-abstractions-code
channels:
  - defaults
dependencies:
- python>=3.7
- pip
- anaconda
- pip:
  - numpy
  - pandas
  - gym
  - graphviz
  - matplotlib
  - seaborn
  # for development
  - jupyter
  - ipython
  # for tests
  - hypothesis
  - pytest
  - pytest-cov
  - pytest-randomly
